server.port=5004
grpc.server.port=5005
jwt.secret=Rh?jkJ4847wBXqvWCB5UbNZDnc&KN7ABxk^dpu43H9@f_Gt@FT@D=yHj?R!^ZTuEHN8Vb36-gNua5aak24fX=&g-+AUmS%?Udm3H6WT7h^W@AMhX!TzfbTCw?Z_XsBj6

spring.data.mongodb.host=localhost
spring.data.mongodb.database=settingsdb
spring.data.mongodb.port=27017

server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:settingsapi.p12
server.ssl.key-store-password=Bibek123@
server.ssl.key-alias=settingsapi
server.ssl.enabled=true
