server.port=5004
grpc.server.port=5005
server.servlet.context-path=/settings
jwt.secret=Rh?jkJ4847wBXqvWCB5UbNZDnc&KN7ABxk^dpu43H9@f_Gt@FT@D=yHj?R!^ZTuEHN8Vb36-gNua5aak24fX=&g-+AUmS%?Udm3H6WT7h^W@AMhX!TzfbTCw?Z_XsBj6

spring.data.mongodb.host=localhost
spring.data.mongodb.database=settingsdb
spring.data.mongodb.port=27017

management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true