apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: settingsapi
spec:
  destination:
    name: settingsapi
  sources:
    - name: tmsolution-gateway
      action: allow
