name: Settings API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    uses: itsbibeksaini/github-actions-workflows/.github/workflows/gradle-build.yml@main
